#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
npm install -g gulp --save
npm install -g gulp-uncss --save
npm install -g gulp-sass --save
npm install -g gulp-concat --save
npm install -g gulp-cssnano --save
gulp